package rs.ac.uns.acs.nais.service;

public enum AssistantIntentType {
    CURRICULUM_LIST,
    SUBJECT_PRESENCE,
    SUBJECT_DETAIL,
    STATISTICS_RANKING,
    STUDENT_ALL,
    STUDENT_PROFILE,
    STUDENT_GRADES,
    STUDENT_GPA,
    UNPASSED_SUBJECTS,
    CURRICULUM_REMAINDER,
    EXAM_ATTEMPTS,
    PASS_ROK_SUMMARY,
    HYBRID_FILTERED_SEMANTIC,
    SEMANTIC_TEXT_SEARCH,
    UNKNOWN
}
