"""Zvanični nazivi predmeta za kurikulum u 02_data.sql (SI, AUT, EE, RT, TK)."""

SI_NAMES = [
    "Matematika 1",
    "Osnove programiranja",
    "Uvod u računarsko inženjerstvo",
    "Linearna algebra",
    "Diskretne strukture",
    "Engleski jezik za inženjere",
    "Matematika 2",
    "Algoritmi i strukture podataka",
    "Objektno orijentisano programiranje",
    "Baze podataka",
    "Verovatnoća i statistika",
    "Operativni sistemi",
    "Računarske mreže",
    "Uvod u softversko inženjerstvo",
    "Veb programiranje",
    "Paralelno programiranje",
    "Kompajleri",
    "Bezbednost računarskih sistema",
    "Testiranje i kvalitet softvera",
    "Distribuirani sistemi i servisi",
    "Upravljanje softverskim projektima",
    "Arhitektura softvera",
    "Cloud računarstvo i virtualizacija",
    "Mobilne platforme i aplikacije",
    "Veštačka inteligencija",
    "Mašinsko učenje u inženjerstvu",
    "Obrada velikih podataka",
    "DevOps i kontinuirana isporuka",
    "Mikroservisna arhitektura",
    "Poslovni i informacioni sistemi",
    "Napredne teme softverskog inženjerstva",
    "Formalne metode u razvoju softvera",
    "Modelovanje poslovnih procesa",
    "Stručna praksa",
    "Priprema završnog rada",
]

AUT_NAMES = [
    "Uvod u automatiku i sistemsko inženjerstvo",
    "Matematika za inženjere automatike",
    "Fizika",
    "Osnove elektrotehnike",
    "Elektronska kola",
    "Merenja i senzori u automatizaciji",
    "Teorija automatskog upravljanja",
    "Dinamika sistema",
    "Digitalna obrada signala – uvod",
    "Programiranje u automatizaciji",
    "Industrijska automatika",
    "PLC sistemi",
    "Aktuatori i električni pogoni",
    "Upravljanje procesima",
    "Modelovanje i simulacija sistema",
    "Nelinearni sistemi upravljanja",
    "Roboti i manipulatori",
    "Inteligentna kontrola",
    "Prediktivno upravljanje",
    "Optimalno upravljanje",
    "Industrijski komunikacioni protokoli",
    "Supervizijski sistemi i SCADA",
    "Bezbednost industrijskih sistema",
    "Sistemi u realnom vremenu",
    "Estimacija stanja i filtri",
    "Adaptivno upravljanje",
    "Upravljanje hibridnim sistemima",
    "Identifikacija dinamičkih sistema",
    "Automatika u procesnoj industriji",
    "Energetski sistemi i regulacija",
    "Mehatronika",
    "Izborni predmet – automatika I",
    "Izborni predmet – automatika II",
    "Praktična nastava u industriji",
    "Timski projekat iz automatike",
    "Diplomski seminar",
    "Primena automatike u praksi",
    "Priprema završnog rada",
]

EE_NAMES = [
    "Matematika za elektrotehničare",
    "Fizika",
    "Osnove elektrotehnike",
    "Električna kola",
    "Elektronika",
    "Digitalna logika",
    "Električna merenja",
    "Teorija elektromagnetnih polja",
    "Elektroenergetski sistemi",
    "Električne mašine i transformatori",
    "Elektronska kola i uređaji",
    "Analogna elektronika",
    "Digitalna elektronika",
    "Mikroprocesorski sistemi",
    "Elektroenergetika – prenos i distribucija",
    "Elektromotorni pogoni",
    "Elektromagnetna kompatibilnost – osnovi",
    "Elektroenergetska elektronika",
    "Električne instalacije i osvetljenje",
    "Telekomunikacije – osnovi",
    "Optičke komunikacije",
    "Antene i prostiranje talasa",
    "Digitalne komunikacije",
    "Obrada signala",
    "Upravljanje električnim pogonom",
    "Analiza električnih mreža",
    "Kvalitet električne energije",
    "Obnovljivi izvori električne energije",
    "Elektronska energetika",
    "Visokonaponska tehnika",
    "Projekat iz elektrotehnike",
    "Izborni predmet EE I",
    "Izborni predmet EE II",
    "Stručna praksa",
    "Timski projekat iz elektrotehnike",
    "Diplomski seminar EE",
    "Napredne teme elektroenergetike",
    "Priprema završnog rada",
]

RT_NAMES = [
    "Matematika 1",
    "Osnove programiranja",
    "Uvod u računarsku tehniku i informatiku",
    "Arhitektura računara",
    "Digitalni sistemi",
    "Elektronika",
    "Mikroprocesori i asembler",
    "Operativni sistemi",
    "Računarske mreže",
    "Ugrađeni računarski sistemi",
    "Programabilna logička kola (FPGA)",
    "Mikrokontroleri",
    "Sistemi u realnom vremenu",
    "Organizacija računara",
    "Interfejsi i sabirnice",
    "Memorijske hijerarhije",
    "Sistemi na čipu",
    "Verifikacija digitalnih sistema",
    "Pouzdanost računarskih sistema",
    "Napajanje digitalnih sistema",
    "Multimedijski hardver",
    "Mrežni ugrađeni sistemi",
    "Internet stvari – platforme",
    "Bezbednost ugrađenih uređaja",
    "Industrijski računarski sistemi",
    "Automatizovano testiranje hardvera",
    "Dizajn štampanih ploča",
    "Projekat iz digitalnog dizajna",
    "Izborni predmet RT I",
    "Izborni predmet RT II",
    "Napredni mikrokontrolerski sistemi",
    "Stručna praksa",
    "Timski hardversko-softverski projekat",
    "Diplomski seminar RT",
    "Virtuelizacija i ugrađeni sistemi",
    "Napredno računarsko modelovanje",
    "VLSI – uvod",
    "Priprema završnog rada",
]

TK_NAMES = [
    "Matematičke metode u telekomunikacijama",
    "Teorija telekomunikacija",
    "Signali i sistemi",
    "Statistička teorija komunikacija",
    "Informacija i kodiranje",
    "Digitalne komunikacije",
    "Analogne komunikacije",
    "Mikrotalasna tehnika",
    "Antenski sistemi",
    "Optičke komunikacije",
    "Mobilne mreže",
    "Mreže sledeće generacije",
    "Širenje talasa u komunikacionim kanalima",
    "Internet mreže i protokoli",
    "Bezbednost komunikacija",
    "Kriptografija u telekomunikacijama",
    "VoIP i multimedijske usluge",
    "Satelitske komunikacije",
    "Radioupravljanje i telemetrija",
    "Kvalitet usluge u mrežama",
    "Upravljanje mrežnim resursima",
    "Bežične senzorske mreže",
    "MIMO sistemi i primene",
    "Napredna obrada signala",
    "Mašinsko učenje u telekomunikacijama",
    "Softver definisan radij",
    "Mrežna funkcionalna virtualizacija",
    "Cloud komunikacijske platforme",
    "IoT mrežna arhitektura",
    "Projektovanje telekomunikacionih sistema",
    "Simulacija komunikacionih kanala",
    "Izborni predmet TK I",
    "Izborni predmet TK II",
    "Izborni predmet TK III",
    "Stručna praksa – telekomunikacije",
    "Timski projekat iz telekomunikacija",
    "Diplomski seminar master TK",
    "Napredne teme optičkih mreža",
    "Priprema master rada",
]
